export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';
export const SEND_GIPHY_REQUEST = 'SEND_GIPHY_REQUEST';
export const GIPHY_REQUEST_SUCESS = 'GIPHY_REQUEST_SUCESS';
export const GIPHY_REQUEST_ERROR = 'GIPHY_REQUEST_ERROR';